### ISSUE TITLE
`get_metadata` broken for some dandisets

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1181] opened 2022-12-26 15:39 UTC
Looking for data with LFP, I'd like to be able to run:

```python
from dandi.dandiapi import DandiAPIClient

ids = [
    dandiset.identifier 
    for dandiset in DandiAPIClient().get_dandisets() 
    if 'LFP' in dandiset.get_metadata().assetsSummary.variableMeasured
]
```

but currently this outputs an error because the metadata object cannot be constructed for all dandisets:

```pytb
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Input In [18], in <cell line: 3>()
      1 from dandi.dandiapi import DandiAPIClient
----> 3 ids = [
      4     dandiset.identifier 
      5     for dandiset in DandiAPIClient().get_dandisets() 
      6     if 'LFP' in dandiset.get_metadata().assetsSummary.variableMeasured
      7 ]

Input In [18], in <listcomp>(.0)
      1 from dandi.dandiapi import DandiAPIClient
      3 ids = [
      4     dandiset.identifier 
      5     for dandiset in DandiAPIClient().get_dandisets() 
----> 6     if 'LFP' in dandiset.get_metadata().assetsSummary.variableMeasured
      7 ]

File /opt/conda/lib/python3.10/site-packages/dandi/dandiapi.py:930, in RemoteDandiset.get_metadata(self)
    925 def get_metadata(self) -> models.Dandiset:
    926     """
    927     Fetch the metadata for this version of the Dandiset as a
    928     `dandischema.models.Dandiset` instance
    929     """
--> 930     return models.Dandiset.parse_obj(self.get_raw_metadata())

File /opt/conda/lib/python3.10/site-packages/pydantic/main.py:526, in pydantic.main.BaseModel.parse_obj()

File /opt/conda/lib/python3.10/site-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Dandiset
license
  ensure this value has at least 1 items (type=value_error.list.min_items; limit_value=1)
```

I will try to use `get_raw_metadata` as a work-around, but I suspect the metadata object is the preferred access pattern.

**Comment by bendichter** [comment] 2022-12-26 16:11
I suspect this is connected to re-generating metadata using the new schema

**Comment by yarikoptic** [comment] 2023-01-23 22:15
#1189 seems of the same kind or even a duplicate of this one and @jwodder noted that indeed `get_raw_metadata` to be used if not carrying about validity of the metadata record.  Feel free to reopen if you feel that smth needs to be done differently.

**Closed by yarikoptic** 2023-01-23 22:15 UTC
