### ISSUE TITLE
Add delay between polls while waiting for asset validation

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-cli#406] opened 2021-02-22 15:51 UTC
Right now, the CLI needs to wait for an asset to validate after uploading. This is what the code looks like:
```
        while True:
            lgr.debug("Waiting for server-side validation to complete")
            resp = self.get(f"/uploads/validations/{filehash}/")
            if resp["state"] != "IN_PROGRESS":
                if resp["state"] == "FAILED":
                    raise RuntimeError(
                        "Server-side asset validation failed!"
                        f"  Error reported: {resp.get('error')}"
                    )
                break
            yield {"status": "validating"}
```
This loop will constantly be executing queries with no delay. Considering that 10 files are uploaded/validated simultaneously, this results in substantial server load and hundreds of GB of log spam per day when large uploads are being done. 

Throttling this loop a little, even `time.sleep(1)`, would go a long way to making the server happier.

**Comment by jwodder** [comment] 2021-02-22 16:14
This appears to be a duplicate of #405.

**Closed** 2021-02-22 16:32 UTC
Labels: duplicate
