### ISSUE TITLE
conda install does not support python 3.9

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#562] opened 2021-04-13 16:14 UTC
reported from a user install.

**Comment by yarikoptic** [comment] 2021-04-13 16:36
yeap, dependencies were not satisfiable last time attempted: https://github.com/conda-forge/dandi-feedstock/pull/22 21 days ago, and I can't decypher that message to see what specifically... hdmf - seems to be version agnostic, h5py and pynwb - seems to have merged 3.9 support.  Trying to make bot to rerun attempt at 3.9 - let's see

**Comment by yarikoptic** [comment] 2021-05-17 17:59
well, "support" is there now as of https://github.com/conda-forge/dandi-feedstock/pull/32 (0.7.0) but the issue is the same - unsatisfiable dependencies. AFAIK nothing we could do ATM and nothing really to do in this repo (conda specific issue should go to https://github.com/conda-forge/dandi-feedstock/)

**Closed by yarikoptic** 2021-05-17 17:59 UTC
