### ISSUE TITLE
validate does not work by using current location or '.'

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#1251] opened 2023-03-18 00:35 UTC
using `dandi validate` or `dandi validate .` inside a dandiset (of type bids in this case) did not do any validation. i can't remember the message fully, but something like there is no dandiset here, which would be surprising since there was a `dandiset.yaml` right there.

**Comment by kabilar** [comment] 2023-12-11 20:12
Hi @satra, thanks for the report.  I was unfortunately not able to reproduce this error with `dandi==0.58.1`.  Running both `dandi validate` and `dandi validate .` resulted in a `SUCCESS` for Dandiset [DANDI:000724](https://dandiarchive.org/dandiset/000724/draft).

```
2023-12-11 14:07:46,898 [ WARNING] No BIDS reference root provided.
2023-12-11 14:07:46,899 [    INFO] No schema path specified, defaulting to the bundled schema, `/Users/kabilar/miniconda3/envs/dandi/lib/python3.10/site-packages/bidsschematools/data/schema`.
2023-12-11 14:07:47,388 [    INFO] SUCCESS: All files are BIDS valid and no BIDS-required files are missing.
No errors found.
2023-12-11 14:07:47,392 [    INFO] Logs saved in /Users/kabilar/Library/Logs/dandi-cli/20231211200745Z-12026.log
```

Perhaps this issue has been solved in a recent release?

**Comment by kabilar** [comment] 2023-12-17 21:34
Hi @satra, I will close this issue based on my above findings, but please reopen if the issue persists.  Thanks.

**Closed by kabilar** 2023-12-17 21:34 UTC
