### ISSUE TITLE
lock Error when calling dandi upload

### ISSUE THREAD

**Issue by kaeldai** [dandi/dandi-cli#238] opened 2020-09-13 18:14 UTC
I'm trying to upload data from the Allen Institute but when I call `dandi upload` I get the following error:

`2020-09-12 10:08:49,180 [    INFO] Found 101 files to consider`
`Error: Failed to lock dandiset 000039`

The repo has already been created: https://gui.dandiarchive.org/#/dandiset/000039/draft. `dandi validate` was successful and my 000036/ directory contains 33 sub-*/ folders with valid sym links.

Thanks,
Kael

**Comment by yarikoptic** [comment] 2020-09-13 20:01
Was there some interrupted upload?
 We definitely should provide more information though on the nature of the existing lock. I will look into fixing it tomorrow, thanks for the report.

**Comment by kaeldai** [comment] 2020-09-13 21:55
I tried a few times throughout the day and still got the same error message. I was doing this through a VPN so the internet was working.

**Comment by yarikoptic** [comment] 2020-09-14 20:42
A little update - instead of just pruning the lock so you could progress forward, @mgrauer will check first on girder server side on what has lead to that stale lock to come to exist, and then we will remove it so you could proceed with the upload.

**Comment by mgrauer** [comment] 2020-09-14 21:58
@yarikoptic We looked in Girder and don't see any lock on that dandiset.

If you go to the [swagger page API endpoint](https://girder.dandiarchive.org/api/v1#!/dandi/dandi_wrapper_0_1_2_3_4_5_6) and run the unlock endpoint, it will say that the dandiset isn't currently locked.

**Comment by yarikoptic** [comment] 2020-09-14 23:01
Thank you Mike! Might then be some other issue (permissions etc) and client being stupid to report it properly, I will later provide further guidance to get closure.

**Comment by yarikoptic** [comment] 2020-09-15 01:05
Dear @kaeldai , please install the version from #239 via e.g. `pip3 install --upgrade git+https://github.com/dandi/dandi-cli@enh-lock2` and rerun the upload. Error message should provide more information then which would help to identify actual problem.

**Comment by kaeldai** [comment] 2020-09-15 01:29
Hi @yarikoptic - I'm now getting a slightly different error message:

`2020-09-14 18:21:30,475 [    INFO] Found 101 files to consider`
`Error: Failed to lock dandiset 000039 due to: You must be logged in.`

My dandi account is linked to my github account. I checked and git's user.name and user.email is correct on the machine I'm trying to run a dandi upload from.

**Comment by yarikoptic** [comment] 2020-09-15 22:02
I have looked through the code and not sure yet how this could happen since we do authenticate into girder first.  Please 
- rerun `pip3 install --upgrade git+https://github.com/dandi/dandi-cli@enh-lock2`
- run your upload as `DANDI_DEVEL=1 dandi -l debug upload --devel-debug [any other options you need]`
- paste (or email me debian@onerussian.com) the log so I could see what is happening with authentication etc

**Comment by kaeldai** [comment] 2020-09-16 03:16
@yarikoptic thanks for all your help. This is the command line output I recieve:

```
2020-09-15 20:11:08,938 [   DEBUG] Running a newer version (0.6.4+2.g51bab5d) of dandi/dandi-cli than available (0.6.4)
2020-09-15 20:11:10,667 [   DEBUG] Establishing a client for https://girder.dandiarchive.org
2020-09-15 20:11:10,906 [   DEBUG] Successfully authenticated using the key
2020-09-15 20:11:11,147 [   DEBUG] Working with collection {'_accessLevel': -1, '_id': '5e59bb0af19e820ab6ea6c62', '_modelType': 'collection', 'created': '2020-02-29T01:14:50.702000+00:00', 'description': '', 'meta': {}, 'name': 'drafts', 'public': True, 'size': 2565925161435, 'updated': '2020-03-03T21:03:41.237000+00:00'}
2020-09-15 20:11:11,590 [    INFO] Found 101 files to consider
2020-09-15 20:11:11,593 [   DEBUG] Trying to acquire lock for 000039
2020-09-15 20:11:11,836 [   DEBUG] Caught exception Failed to lock dandiset 000039 due to: You must be logged in.
Traceback (most recent call last):
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/dandi/girder.py", line 512, in lock_dandiset
    resp = self.post(f"dandi/{dandiset_identifier}/lock")
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/girder_client/__init__.py", line 479, in post
    data=data, json=json, headers=headers, jsonResp=jsonResp)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/girder_client/__init__.py", line 465, in sendRestRequest
    response=result)
girder_client.HttpError: HTTP error 401: POST https://girder.dandiarchive.org/api/v1/dandi/000039/lock
Response text: {"message": "You must be logged in.", "type": "access"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local1/.local/miniconda3/envs/nwb_conversion/bin/dandi", line 8, in <module>
    sys.exit(main())
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/dandi/cli/base.py", line 106, in wrapper
    return f(*args, **kwargs)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/dandi/cli/cmd_upload.py", line 101, in upload
    devel_debug=devel_debug,
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/dandi/upload.py", line 519, in upload
    with out, client.lock_dandiset(dandiset.identifier):
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/local1/.local/miniconda3/envs/nwb_conversion/lib/python3.6/site-packages/dandi/girder.py", line 517, in lock_dandiset
    f"Failed to lock dandiset {dandiset_identifier} due to: {msg}"
dandi.exceptions.LockingError: Failed to lock dandiset 000039 due to: You must be logged in.
```

**Comment by yarikoptic** [comment] 2020-09-16 03:37
Thank you. So session is authenticated. @mgrauer - anything in the logs could some the light why user can't lock dandiset? is it about login to django? May be owned by another user or scope is insufficient (in either of those cases error message isn't corresponding to the actual problem)

**Comment by mgrauer** [comment] 2020-09-16 15:21
I believe this is an API key issue, the dandi cli API key now needs a full scope because of changes introduced with locking, but previous keys had custom scopes.

I deleted kaeldai's old key in Girder (description of this below for reference). @kaeldai can you go into gui.dandiarchive.org and log in, and click on your user initials at the top right, there will be a dropdown, the first row is the apikey, click the refresh button (the circled arrow) and this will generate a new key with you that has full scope. Use this new apikey with the CLI, and see if this works.

Thanks for your patience!




<details>
<summary>Description of api key deletion, for a user</summary>

This will also work if you are a Girder admin as you have the ability to delete other users' keys, as I did in this case.

Log into `https://girder.dandiarchive.org/` with the same credentials as you log into `gui.dandiarchive.org`.

Click on the dropdown under your username for `My account`

<img width="198" alt="Screen Shot 2020-09-16 at 11 09 43 AM" src="https://user-images.githubusercontent.com/595023/93356735-8f42bb80-f80d-11ea-877c-0b1d0e2b6a26.png">

Then click on the `API keys` tab, and you'll see a apikey named dandicli. Yours currently says custom scopes, but we need a key with full access. Delete that api key.


<img width="1275" alt="Screen Shot 2020-09-16 at 11 17 39 AM" src="https://user-images.githubusercontent.com/595023/93357682-98805800-f80e-11ea-9588-9fe0296210cb.png">


</details>

**Comment by kaeldai** [comment] 2020-09-16 16:56
@yarikoptic @mgrauer Thanks, that seems to have done the trick and the upload seems to have been successful.

**Comment by yarikoptic** [comment] 2020-09-16 17:18
GREAT!
@mgrauer THANK YOU for tracking it down.   Closing it now and will merge #239 since would be generally useful

Note: In "no-girder" reimplementation of API/backend we must make sure that error messages provided back are more descriptive of the cause which possibly lead to the error message.

**Closed by yarikoptic** 2020-09-16 17:18 UTC

**Comment by mgrauer** [comment] 2020-09-16 17:22
I'm wondering what we should do for the rest of the users who will run into this.

Should we go through all of the existing api keys and delete any dandicli keys that don't have full access? Let people run into the issue and then provide guidance? Provide some message in the cli to suggest this as a fix? 

What do you think @yarikoptic ?

**Comment by yarikoptic** [comment] 2020-09-16 18:57
If error message (from dandiarchive's girder extension?) could be adjusted to say that (instead of just "must be logged in") -- then with #239 now merged (and hopefully soon released), users would see that message.

**Comment by mgrauer** [comment] 2020-09-16 19:09
This message comes from upstream girder, i'm not able to change that in the dandiarchive girder plugin.
