### ISSUE TITLE
Analyze and possibly speed up testing

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#946] opened 2022-04-05 19:39 UTC
@satra raised concern in https://github.com/dandi/dandischema/pull/128#issuecomment-1086380260  and since we (or well, I) enforce our goodness of downstream testing against dandi-cli upon other components, it would be great to indeed ensure that we do not impair DX.  Need to 
- analyze what tests/fixtures we spend most time on?
- analyze and implement what could be speed up to speed up testing?

there was effort/attempt to parallelize testing (#194) which IIRC encountered a "show stopper" at that point, may be worth resurrecting since most of the tests are probably bottlenecking in IO and parallelization should have positive effect.

**Comment by jwodder** [comment] 2022-04-06 15:06
From running the tests locally, the slowest 10 durations as reported by pytest are:

```
============================= slowest 10 durations =============================
43.32s call     dandi/tests/test_bids_validator_xs.py::test_bids_datasets
42.35s call     dandi/tests/test_validate.py::test_validate_bids
31.97s setup    dandi/tests/test_dandiapi.py::test_upload
14.49s call     dandi/tests/test_dandiapi.py::test_publish_and_manipulate
11.70s teardown dandi/tests/test_validate.py::test_validate_bids
8.49s call     dandi/tests/test_upload.py::test_upload_different_zarr_entry_conflicts
8.14s call     dandi/tests/test_dandiapi.py::test_get_dandiset_published_other_version[True]
8.05s call     dandi/tests/test_upload.py::test_upload_different_zarr_file_to_parent_dir
7.14s call     dandi/tests/test_download.py::test_download_newest_version
6.65s call     dandi/tests/test_dandiapi.py::test_get_dandiset_published_other_version[False]
```

Note that the "setup" and "teardown" entries are actually for the setup & teardown of the Dockerized dandi-archive environment.

**Comment by yarikoptic** [comment] 2022-04-13 16:41
@TheChymera we might need to look into making bids testing leaner

**Comment by TheChymera** [comment] 2022-04-18 10:24
one thing I can do is strip [the current testdata repo](https://github.com/dandi/bids-examples) down to a smaller amount of datasets. Other than that, they can probably also be parallelized, but validation is pretty quick at this stage so it's mainly download.

**Comment by TheChymera** [comment] 2022-04-18 10:33
https://github.com/dandi/bids-examples/commit/0553aef7d9e7e1d5f042f54178a3a0b31e92bf16 took it down from 34s locally to 24s — another thing that's taking a bit is the full debugging output to stdout. I could:

(1) remove it entirely from the validator (don't really like the idea, it's pretty useful particularly as we're still working on it)
(2) remove it from testing.

**Comment by TheChymera** [comment] 2022-04-18 10:59
as of https://github.com/dandi/bids-examples/commit/9ed6649d2e14eec7fc7f0e5b2f1f11b7422af4d2 and https://github.com/dandi/dandi-cli/pull/955/commits/ca6e93d84817b9db70ee35cf2408277cce1f54cf it's down to 15s locally. Wouldn't strip it any furhter since we need datasets from different modalities.

**Comment by yarikoptic** [comment] 2022-04-18 13:35
Hm, I don't think it is worth stripping down datasets as the primary strategy to speed things up.  Do you know why it takes that while to go through them? :  
- Is it IO or CPU bound? 
- If you run `py-spy` on that test process - what takes most of the time (regex matching?)?
and then address corresponding bottle neck.

If we are to skip some datasets, just "code that in" in our tests: I would advise to avoid changing https://github.com/dandi/bids-examples beyond "add few of our custom ones" so we could later easily update for new example datasets etc.  As for how to "code that in" -- @jwodder , please advise on what would be the best way to orchestrate with pytest and our `bids_examples` fixture so unless some option is given to pytest (e.g., `all_bids_examples` mark), then 
```
dandi/tests/test_validate.py:def test_validate_bids(bids_examples):
```
runs only a list of specific datasets there, not all.

**Comment by yarikoptic** [comment] 2022-04-18 13:38
@jwodder please also look into possibly optimizing
```
31.97s setup    dandi/tests/test_dandiapi.py::test_upload
14.49s call     dandi/tests/test_dandiapi.py::test_publish_and_manipulate
```
[you listed](https://github.com/dandi/dandi-cli/issues/946#issuecomment-1090380173) . For `setup` -- what is spent time in docker compose -- to provision the environment? (then may be we could look into minimizing that) or some other steps?

In the test -- Is it a matter of file sizes for upload? slowness of API? or something else?

**Comment by jwodder** [comment] 2022-04-18 13:41
@yarikoptic

* `test_validate_bids` already limits what entries in `bids_examples` it validates to a fixed list.  Exactly what use do you envision for adding a option for testing custom sets of examples?
* `setup` is largely multiple calls to `docker-compose`; I'm not sure which one takes the longest.
* `test_publish_and_manipulate` publishes a Dandiset (which means waiting for the Dockerized server to validate it) and also uploads & downloads to it several times.

**Comment by yarikoptic** [comment] 2022-04-18 14:00
> * `test_validate_bids` already limits what entries in `bids_examples` it validates to a fixed list.  Exactly what use do you envision for adding a option for testing custom sets of examples?

my bad -- I should have looked inside. indeed there is some whitelist.  Then I guess I am confused on what   @TheChymera was trying to achieve in [stripping datasets away](https://github.com/dandi/dandi-cli/issues/946#issuecomment-1101299030).  @TheChymera -- were you removing files within those datasets??

Also @TheChymera  confusingly apparently there are two tests doing the same thing I think with just different "validation" entry points:

- https://github.com/dandi/dandi-cli/blob/HEAD/dandi/tests/test_validate.py#L4  - `from dandi.validate import validate_bids`
- https://github.com/dandi/dandi-cli/blob/HEAD/dandi/tests/test_bids_validator_xs.py#L291 - `from dandi.bids_validator_xs import validate_bids`  + has some more tests

what is the point/need in having both of them?

Also I would recommend to move https://github.com/dandi/dandi-cli/blob/HEAD/dandi/tests/test_bids_validator_xs.py#L323 portion of that test into a dedicated test (eg. test_bids_datasets_selected_paths) . Probably moving out `whitelist` into module wide `BIDS_EXAMPLES_WHITELIST` constant to reuse across tests.  Then we would also see how long that particular portion of the test takes

**Comment by yarikoptic** [comment] 2022-04-18 14:05
@jwodder 

> * `setup` is largely multiple calls to `docker-compose`; I'm not sure which one takes the longest.

Please time then (`print` statements or some https://github.com/pyutils/line_profiler or alike could come handy) and see how long each one takes 

> * `test_publish_and_manipulate` publishes a Dandiset (which means waiting for the Dockerized server to validate it) and also uploads & downloads to it several times.

good, very good test. Similarly -- what takes most of the time, anything in particular which we might see possible to optimize?

**Comment by jwodder** [comment] 2022-04-18 15:21
@yarikoptic 

* Timings of `setup` steps (in seconds):
    * `manage.py migrate`: 18.001302003860474
    * `manage.py createsuperuser`: 3.3786816596984863
    * `manage.py drf_create_token`: 3.290635108947754
    * `up -d`: 2.275557279586792
    * Waiting for containers to be ready: 4.523201942443848
* Timings of major `test_publish_and_manipulate` steps (in seconds):
    * initial upload: 1.5072083473205566
    * wait_until_valid(): 2.692340850830078
    * publish(): 0.2717759609222412
    * Download published version: 1.2773911952972412
    * Upload modified draft: 0.9313299655914307
    * Download published version: 1.1366846561431885
    * Upload modified draft: 1.025101900100708
    * Download draft version: 1.8018062114715576
    * Download published version: 1.4370958805084229
    * Download draft version: 1.2907021045684814
    * Download published version: 1.350187063217163

**Comment by yarikoptic** [comment] 2022-04-18 19:21
So the major contributor of setup is `manage.py migrate: 18.001302003860474`.  I wonder if it does migrate something and we just need may be to update starting state or what does it really do for over half a minute?

All downloads take over a second, so might be worth looking into a singular download -- what makes it take that long,  it must not be data size which must be tiny, right?

**Comment by AlmightyYakob** [comment] 2022-04-19 16:51
> > I wonder if it does migrate something and we just need may be to update starting state or what does it really do for over half a minute?
> 
> cc @dchiquito @AlmightyYakob @mvandenburgh

`migrate` is populating the empty postgres database with all required models (and possibly other steps to represent a default app). If you wanted to skip `migrate` you'd need to run `migrate` beforehand and re-use that same postgres database. This presents a couple of problems:

1. You'd need to have one test database that you hosted somewhere for this purpose, since the tests are bringing up an empty postgres db every time. This would also potentially present issues with concurrent access by tests running at the same time, conflicts, etc.
2. You'd need to determine when to actually run new migrations, since if we add any migrations they need to be updated in that test postgres db. This could likely be accomplished with CI.

I'm not sure why it's taking 18 seconds, but it's not _too_ surprising.

**Comment by mvandenburgh** [comment] 2022-04-19 16:59
We could also try squashing the migrations. Not sure what kind of speed up it would give, but it would probably do something.

**Comment by yarikoptic** [comment] 2022-04-19 18:27
I do not quite get why there would be any problem @AlmightyYakob mentions [above](https://github.com/dandi/dandi-cli/issues/946#issuecomment-1102873806) if we pre-migrate and save that docker image for reuse as the image instead of redoing migrations every time...

are migrations  "idempotent" (can I run `migrate` multiple times without changes to  arrive to the same result or no action in subsequent?) and "incremental" (if we pre-migrate and I run with some newer set of migrations -- would then only not previously applied apply)?

**Comment by yarikoptic** [comment] 2022-04-19 18:29
> I do not quite get why there would be any problem @AlmightyYakob mentions [above](https://github.com/dandi/dandi-cli/issues/946#issuecomment-1102873806) if we pre-migrate and save that docker image for reuse as the image instead of redoing migrations every time...

doh -- I probably forgot that we are talking about "volumes" and not images here so I am now not even sure how we could ship pre-migrated volume.

**Comment by jwodder** [comment] 2022-04-19 18:30
My understanding is that database migrations themselves are only necessary if the database is using an old version of the application's DB schema.  Does Django not have a way to instantiate a database using just the current model definitions, thereby obviating the need for migrations?

**Comment by AlmightyYakob** [comment] 2022-04-19 20:43
> are migrations "idempotent" (can I run `migrate` multiple times without changes to arrive to the same result or no action in subsequent?) and "incremental" (if we pre-migrate and I run with some newer set of migrations -- would then only not previously applied apply)?

The answer to both of these questions is yes.


> My understanding is that database migrations themselves are only necessary if the database is using an old version of the application's DB schema. Does Django not have a way to instantiate a database using just the current model definitions, thereby obviating the need for migrations?


Migrations will always be needed on a fresh postgres database, since migrations are what populates the database with the required tables and relationships that the applications needs to function. Django does have a way to create these migrations automatically based on model definitions (`manage.py makemigrations`, indeed what we use anytime we add/modify/delete models), but there are also some hand written migrations in our app which are required for full functionality.


IMO, I'm not really sure any of this would make much of a difference for CLI test timing. Pulling from the last run of the CLI tests in our CI (https://github.com/dandi/dandi-archive/runs/6084842248?check_suite_focus=true), the tests take almost 7 minutes to run. Shaving off even the full 18 seconds wouldn't really matter much here, since `migrate` is only run once, before the tests begin.

**Comment by TheChymera** [comment] 2022-04-20 13:17
For the BIDS part at least, looking into this over here. Draft for now, more might come later. https://github.com/dandi/dandi-cli/pull/965

**Comment by yarikoptic** [comment] 2022-04-21 22:36
@TheChymera Did you try to py-spy the BIDS testing to assess what most of the time is spent on?

**Comment by TheChymera** [comment] 2022-04-25 06:27
@yarikoptic so it seems that match is taking no time at all, and a lot of overhead is coming from `ruamel-yaml`.

This is the output of:
```
py-spy top -- pytest -vvs tests/test_bids_validator_xs.py::test_bids_datasets
```
https://ppb.chymera.eu/0e2847.md


This is the output of:
```
py-spy record --format speedscope -o profile.svg -- pytest -vvs tests/test_bids_validator_xs.py::test_bids_datasets
```
https://ppb.chymera.eu/bf78ac.svg (can be opened with https://www.speedscope.app/ ).

No idea what to do about this, or whether the issue is with:
* my usage of the upstream BIDS code
* the upstream BIDS code
* someting in `ruamel-yaml`

All the functions listed under the load section seem to be `ruamel-yaml` internals — particularly check_event `(ruamel/yaml/parser.py:146)`. To be fair both my code and the BIDS code does a bit of iteration over the dictionary, but I don't think that should show up as belonging to the YAML parser.

Also the evaluation makes it look like `load_all` is run twice for each dataset. Not sure why, I checked manually and it only runs once.

**Comment by TheChymera** [comment] 2022-04-25 06:58
Hmmmm indeed it seems to be half from me:

```console
chymera@decohost ~/src/dandi-cli $ time python -c "from dandi import bids_validator_xs; bids_validator_xs.load_all('dandi/support/bids/schemadata/1.7.0+012+dandi001/')"

real	0m1.926s
user	0m1.886s
sys	0m0.040s

chymera@decohost ~/src/dandi-cli $ time python -c "from dandi.support.bids import schema; schema.load_schema('dandi/support/bids/schemadata/1.7.0+012+dandi001/')"

real	0m1.125s
user	0m1.087s
sys	0m0.038s
```

The issue seems to have been that although `dandi.bids_validator_xs.load_all()` is only run once, it runs `dandi.support.bids.schema.load_schema()` internally due to carry-over from an older logic. 

Fixed in https://github.com/dandi/dandi-cli/pull/982 but might not improve it by more than 50%. Maybe that's ok?

**Comment by TheChymera** [comment] 2022-04-25 07:13
> 18.07s call     dandi/tests/test_bids_validator_xs.py::test_bids_datasets

vs.

> 31.65s call     dandi/tests/test_bids_validator_xs.py::test_bids_datasets

Still the slowest test, but yes, went down by almost 50%.
Beyond this we probably need to look at `ruamel-yaml`, since the BIDS code seems pretty straight-forward.

**Comment by TheChymera** [comment] 2022-04-26 06:09
After the merged PR, there doesn't seem to be any obvious main time hog any more. The entire validation seems to take around 1s for all datasets, and before that there are about 2s more chalked up to pytest internals such as `parse (/usr/lib/python3.9/site-packages/_pytest/config/__init__.py:1304)`.

**Comment by jwodder** [comment] 2022-07-27 15:18
@yarikoptic Is there anything to still do for this issue?

**Closed** 2022-12-07 20:50 UTC
Labels: tests
